### ISSUE TITLE
Specify Additional `NetworkPolicy` Permitting Workloads Access to Load Balancer

### ISSUE THREAD

**Issue by axisofentropy** [UffizziCloud/uffizzi-cluster-operator#47]
The default `NetworkPolicy` for customer workloads set by the vCluster Helm Chart prohibits customer Pods from contacting our load balancer, which is presently `ingress-nginx`. Unfortunately that Helm Chart is not flexible enough to easily add additional rules to this `NetworkPolicy`, but my testing suggests that we may specify an additional `NetworkPolicy` permitting this access and the two will merge.

Background Slack threads:
- https://uffizzi-internal.slack.com/archives/CN8MKSAQ5/p1692407086615609
- https://uffizzi-internal.slack.com/archives/C85U32F3M/p1692722374733979

Just after creating the `HelmRelease` resource, create an additional `NetworkPolicy` object much like this example:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: uc-antonetta-cormier-workloads-ingress
  namespace: c473
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    - port: 80
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: controller
          app.kubernetes.io/name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: uffizzi
  podSelector:
    matchLabels:
      vcluster.loft.sh/managed-by: uc-antonetta-cormier
  policyTypes:
  - Egress
```
Note that the example string `uc-antonetta-cormier` must be substituted in both `metadata.name` and `spec.egress.podSelector.matchLabels` with the `name` of the `HelmRelease`. The rest can be applied verbatim.

(It would be nice to future proof by more dynamically fetching the `name` of the `Namespace` where `ingress-nginx` is running, but I don't know of a great way to discover that without introducing more risk than it mitigates. If that Namespace ever changes we'll figure this out during integration testing. Maybe set `uffizzi` as a constant?)
