### ISSUE TITLE
Back `k3s` with `etcd` 

### ISSUE THREAD

**Issue by axisofentropy** [UffizziCloud/uffizzi-cluster-operator#57]
Long Slack thread https://uffizzi-internal.slack.com/archives/C85U32F3M/p1695330070138869

By default, k3s uses embedded SQLite as its database. In my testing, k3s performs much better when using etcd, and the combined containers use much less CPU and memory than SQLite. We should consider using this for some or all uCluster customers.

This option is documented by vCluster here: https://www.vcluster.com/docs/operator/external-datastore

and by the Rancher k3s team here: https://docs.k3s.io/datastore

To configure this, our operator should deploy etcd into the customer namespace on our host cluster just before it deploys vCluster. This is probably best done by creating a `HelmRelease` resource for the bitnami etcd Helm chart: https://artifacthub.io/packages/helm/bitnami/etcd

For the first iteration we can try values like these:
```yaml
global:
  storageClass: "premium-rwo"
replicaCount: 1
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 5
persistence:
  size: "10Gi"
tolerations:
- effect: NoSchedule
  key: sandbox.gke.io/runtime
  operator: Exists
nodeSelector:
  sandbox.gke.io/runtime: gvisor
auth:
  rbac:
    create: false
resources:
  limits:
    cpu: 500m
    memory: 800Mi
  requests:
    cpu: 100m
    memory: 200Mi
```

We'll also need to change the values for our vCluster Helm release, including these:

```yaml
enableHA: true
vcluster:
  env:
  - name: K3S_DATASTORE_ENDPOINT
    value: http://my-etcd:2379
storage:
  persistence: false
```
(no other attributes within `storage:`.)

IF we decide to offer this for some customers but not others, we should probably add options to our `UffizziCluster` interface, with choices for using etcd or sqlite, the number of replicas for both k3s and etcd, the size and speed of the etcd volume, etc. That may or may not be outside the scope of this ticket.

**Comment by axisofentropy** [comment]
I explored using etcd embedded within k3s. It performed well but their interface doesn't help and they don't support exactly what we want. https://rancher-users.slack.com/archives/CGGQEHPPW/p1696003681817749

**Comment by axisofentropy** [comment]
performance profiling from Slack thread:

> Running two ingress-nginx e2e test runs with only 7 parallel runners.
> 
> First uCluster: unmodified k3s with default SQLite:
> - peak just under 1 vCPU, average around half
> - around 1GiB memory and slowly rising
> - peak IOPS 5000 ("balanced" GCE volume)
> 
> Second uCluster: single k3s with single etcd:
> - etcd utilization: 0.13 vCPU, 0.13 GiB
> - k3s utilization: 0.37 vCPU, 0.5 GiB
> - peak 250 IOPS ("ssd" GCE volume)

**Comment by axisofentropy** [comment]
This may increase uCluster provisioning time, especially for etcd deployments with multiple replicas. Probably less than two minutes at most. I can profile this more if that's a concern.

**Comment by jpthurman** [comment]
We need a provisioning speed test with the etcd to make a final decision on if etcd is default or if we want to make it an option.

**Comment by jpthurman** [comment]
@gadkins from @axisofentropy thread on Slack https://uffizzi-internal.slack.com/archives/C85U32F3M/p1696870804707309

etcd/vcluster HelmRelease provisioning speed testing:
vcluster w/ settings we're using now: 80 seconds
3 replica etcd: 60 seconds
1 replica etcd: 60 seconds
vcluster connecting to etcd, specified simultaneously: 75 seconds

we get better perfomance. the automated testing can work slowly without etcd, but needs etcd's increased performance to achieve our 10-20 minute targets for ingress-nginx.

**Comment by jpthurman** [comment]
Based on the recommendation above we should make etcd the default option on Uffizzi.  

Later we can offer variations with SQLite, Postgres etc

**Comment by waveywaves** [comment]
#65 #66 #67 #68 #69 #70 #71

**Comment by axisofentropy** [comment]
@waveywaves sorry it looks like the vcluster chart values I gave you are not producing what we want, at least not with `v0.16.4`. The resulting `vcluster` Pods are mounting a temporary `emptyDir` and using it for bootstrap data including their certificates, I think? This means that when they restart they generate new certificates and existing clients cannot connect to them.

What's working in my testing this morning is:
```yaml
enableHA: false
storage:
  persistence: true
```
and make sure the value of `K3S_DATASTORE_ENDPOINT` begins with `http://`!

It looks like this does create a `StatefulSet` and _maybe_ stores bootstrap certificates on a PVC. But I can also see that it's using `etcd` and storing most state in there.
