### ISSUE TITLE
Better handle multiple hostnames in synchronized Ingress

### ISSUE THREAD

**Issue by axisofentropy** [UffizziCloud/uffizzi-cluster-operator#76]
Builds upon #42 

Just now I tested an Ingress for @copytesting that had multiple hostnames. Our plugin dutifully changed all of them... to the same value.  This could probably be improved by making each one unique in some way, preferably using some part of the initially specified hostname.

Example to test:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
  name: ship-too
  namespace: app
spec:
  ingressClassName: uffizzi
  rules:
  - host: demo
    http:
      paths:
      - backend:
          service:
            name: web
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: demo-api
    http:
      paths:
      - backend:
          service:
            name: api
            port:
              number: 80
        path: /
        pathType: Prefix
```

Our plugin changed it to this:
```yaml
spec:
  ingressClassName: uffizzi
  rules:
  - host: ship-too-app-pr-3426-c2021.uclusters.app.uffizzi.com
    http:
      paths:
      - backend:
          service:
            name: web
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: ship-too-app-pr-3426-c2021.uclusters.app.uffizzi.com
    http:
      paths:
      - backend:
          service:
            name: api
            port:
              number: 80
        path: /
        pathType: Prefix
```

If each of those hostnames were unique, I think that would be an improvement.

# Workaround

Splitting this Ingress up into multiple Ingresses would probably Work without modifying our plugin. We may end up doing this for this client so I'm not sure of the urgency here.
